language: python
python:
  - "2.7"
install:
  - git clone https://github.com/tabatkins/bikeshed.git
  - pip install --editable $PWD/bikeshed
  - pip install docutils
  - bikeshed update
script:
  - bash .deploy/deploy.sh
env:
  global:
    - ENCRYPTION_LABEL: "a8360f977eef"
    - COMMIT_AUTHOR_EMAIL: "hcedwar@sandia.gov"
